### PR TITLE
Install SlicerExecutionModel and build c++ CLIs (Rev #2)

### PR DESCRIPTION
**Pull request by jcfr**

### CODE REVIEW

**Comment by jcfr** [comment]
@cdeepakroy  I am testing locally, will integrate as soon as the Docker build complete

**Comment by jcfr** [comment]
The image now build successfully :fireworks: 

One last issue with the entrypoint when trying to run c++ CLI, I remember fixing a similar issue when setting up demo for the Medical WebApp hackfest, will retrieve the fix.

```
$ docker run  girder/slicer_cli_web_plugin
usage: cli_list_entrypoint.py [-h] [--list_cli] <cli>
cli_list_entrypoint.py: error: too few arguments
```

```
$ docker run  girder/slicer_cli_web_plugin --list_cli
{
  "sample_python_cli": {
    "type"    : "python"
  },

  "sample_cpp_cli": {
    "type"    : "cxx"
  }
}
```

```
$ docker run  girder/slicer_cli_web_plugin sample_python_cli --help
No handlers could be found for logger "ctk_cli.module"
usage: sample_python_cli.py [-h] [-V] [--xml] [--returnparameterfile <file>]
                            [--boolean1 <boolean>] [--boolean2 <boolean>]
                            [--boolean3 <boolean>] [-d <double>]
                            [--directory1 <directory>]
                            [-e {Ron,Eric,Bill,Ross,Steve,Will}]
                            [-f <float-vector>] [--file1 <file>]
                            [--files <file>] [-i <integer>] [--image1 <image>]
                            [--image2 <image>]
                            [--string_vector <string-vector>]
                            arg0 arg1
[...]

Description: Sample slicer CLI in Python that shows one of each type of
parameter.

Author(s): Deepak Roy Chittajallu (Kitware)

Acknowledgements: This work is part of the National Alliance for Medical Image
Computing (NAMIC), funded by the National Institutes of Health through the NIH
Roadmap for Medical Research, Grant U54 EB005149.
```

```
$ docker run  girder/slicer_cli_web_plugin sample_cpp_cli --help
Traceback (most recent call last):
  File "/build/slicer_cli_web/server/cli_list_entrypoint.py", line 102, in <module>
    CLIListEntrypoint()
  File "/build/slicer_cli_web/server/cli_list_entrypoint.py", line 93, in CLIListEntrypoint
    subprocess.call(script_file + sys.argv[2:])
TypeError: cannot concatenate 'str' and 'list' objects
```

**Comment by jcfr** [comment]
Et voila, the list issue is fixed by https://github.com/girder/slicer_cli_web/pull/8

**Comment by cdeepakroy** [comment]
Thanks JC! I will create a Dockerfile in `girder/slicer_cli_web` and move installation of `conda, cmake, ITK, SlicerExectionModel, and ctk_cli` to that Dockerfile. That way all plugins can derive from that docker image, which will make the the Dockerfile of plugins look very simple.

**Pull request merged**
